### PR TITLE
Use localectl on rhel 7+

### PR DESCRIPTION
**Pull request by realloc**
Use localectl on rhel 7+

### CODE REVIEW

**Comment by jacobvosmaer** [comment]
:+1: this cookbook errors out on RHEL 7 because `/etc/sysconfig/i18n` does not exist.

**Comment by sahilm** [comment]
Any news on when this can be merged?

**Comment by chewi** [comment]
To be honest, you should probably use localectl on any platform using systemd, including Debian. You can check for this with `node['init_package'] == 'systemd'`. Debian still uses `/etc/default/locale` rather than `/etc/locale.conf` though. I was going to make these changes myself but I'm still struggling to get things to work the way I expect. I don't need this badly enough so I'm giving up for now, sorry!

**Comment by lamont-granquist** [comment]
#20

**Pull request closed without merging**
